package Telas;

import Classes.ConexaoSQL;
import Classes.Fornecedor;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author 2830482411041
 */
public class CadastroFor extends javax.swing.JFrame {

    // Lista estática para guardar os fornecedores
    private static List<Fornecedor> fornecedores = new ArrayList<>();

    public static List<Fornecedor> getFornecedores() {
        return fornecedores;
    }
    public CadastroFor() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

        private void apenasNum(java.awt.event.KeyEvent evt) {
            char c = evt.getKeyChar();
            if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
                evt.consume();
            }
        }
        
        private boolean validarCampos() {
        if (txtCodigofor.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, preencha o código do fornecedor!", 
                "Campo obrigatório", 
                JOptionPane.WARNING_MESSAGE);
            txtCodigofor.requestFocus();
            return false;
        }
        
        if (txtNomefor.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, preencha o nome do fornecedor!", 
                "Campo obrigatório", 
                JOptionPane.WARNING_MESSAGE);
            txtNomefor.requestFocus();
            return false;
        }
        
        if (txtNomefant.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, preencha o nome fantasia do fornecedor!", 
                "Campo obrigatório", 
                JOptionPane.WARNING_MESSAGE);
            txtNomefant.requestFocus();
            return false;
        }
        
        if (txtCepfor.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, informe o CEP do fornecedor!", 
                "Campo obrigatório", 
                JOptionPane.WARNING_MESSAGE);
            txtCepfor.requestFocus();
            return false;
        }
        
        if (txtNumfor.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, informe o número do endereço!", 
                "Campo obrigatório", 
                JOptionPane.WARNING_MESSAGE);
            txtNumfor.requestFocus();
            return false;
        }
        
        if (txtEmailfor.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, informe o email do fornecedor!", 
                "Campo obrigatório", 
                JOptionPane.WARNING_MESSAGE);
            txtEmailfor.requestFocus();
            return false;
        }
        
        if (txtTelfor.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, informe o telefone do fornecedor!", 
                "Campo obrigatório", 
                JOptionPane.WARNING_MESSAGE);
            txtTelfor.requestFocus();
            return false;
        }
        
        if (txtCNPJfor.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, informe o telefone do fornecedor!", 
                "Campo obrigatório", 
                JOptionPane.WARNING_MESSAGE);
            txtCNPJfor.requestFocus();
            return false;
        }
        
        return true;
    }

    
    /* Verifica se o código já existe na lista de produtos
     * return true se já existe, false caso não exista
     */
    private boolean codigoJaExiste(String codigo) {
        for (Fornecedor p : fornecedores) {
            if (p.getCodigo().equals(codigo)) {
                return true;
            }
        }
        return false;
    }
    
    private void limparCampos() {
        txtCodigofor.setText("");
        txtNomefor.setText("");
        txtNomefant.setText("");
        txtEmailfor.setText("");
        txtNumfor.setText("");
        txtCepfor.setText("");
        txtTelfor.setText("");
        txtCNPJfor.setText("");
        txtCodigofor.requestFocus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNomefor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCodigofor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCNPJfor = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtNomefant = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtNumfor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCepfor = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtTelfor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEmailfor = new javax.swing.JTextField();
        clearforbTn = new javax.swing.JButton();
        saveforbTn = new javax.swing.JButton();
        forcadbTn = new javax.swing.JButton();
        returnbTnfor = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel13.setText("Nome fantasia:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(74, 85, 104));

        jPanel1.setBackground(new java.awt.Color(245, 158, 11));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(483, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pczinho\\Downloads\\JAVAprojeto\\JAVAprojeto\\src\\icons\\icone_fornecedor.png")); // NOI18N
        jLabel1.setText("Cadastro de Fornecedores");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIconTextGap(8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(74, 85, 104));
        jPanel2.setForeground(new java.awt.Color(74, 85, 104));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(74, 85, 104));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel3.setForeground(new java.awt.Color(74, 85, 104));
        jPanel3.setOpaque(false);

        jPanel4.setBackground(new java.awt.Color(74, 85, 104));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(245, 158, 11)));
        jPanel4.setForeground(new java.awt.Color(245, 158, 11));
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabel3.setBackground(new java.awt.Color(245, 158, 11));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Dados gerais");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel5.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setText("Código do fornecedor:");

        txtNomefor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNomefor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 224, 224), 2, true));
        txtNomefor.setPreferredSize(new java.awt.Dimension(5, 30));
        txtNomefor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeforActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setText("Nome:");

        txtCodigofor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCodigofor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 224, 224), 2, true));
        txtCodigofor.setPreferredSize(new java.awt.Dimension(5, 30));
        txtCodigofor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoforActionPerformed(evt);
            }
        });
        txtCodigofor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoforKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setText("Nome fantasia:");

        txtCNPJfor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCNPJfor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 224, 224), 2, true));
        txtCNPJfor.setPreferredSize(new java.awt.Dimension(5, 30));
        txtCNPJfor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCNPJforActionPerformed(evt);
            }
        });
        txtCNPJfor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCNPJforKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel14.setText("CNPJ:");

        txtNomefant.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNomefant.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 224, 224), 2, true));
        txtNomefant.setPreferredSize(new java.awt.Dimension(5, 30));
        txtNomefant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomefantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNomefor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtCNPJfor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtCodigofor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel14))
                .addGap(0, 211, Short.MAX_VALUE))
            .addComponent(txtNomefant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigofor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomefor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomefant, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCNPJfor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.setOpaque(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setText("CEP:");

        txtNumfor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNumfor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 224, 224), 2, true));
        txtNumfor.setPreferredSize(new java.awt.Dimension(5, 30));
        txtNumfor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumforActionPerformed(evt);
            }
        });
        txtNumfor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumforKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setText("Número:");

        txtCepfor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCepfor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 224, 224), 2, true));
        txtCepfor.setPreferredSize(new java.awt.Dimension(5, 30));
        txtCepfor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCepforActionPerformed(evt);
            }
        });
        txtCepfor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCepforKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNumfor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtCepfor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCepfor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumfor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(74, 85, 104));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(245, 158, 11)));
        jPanel7.setForeground(new java.awt.Color(245, 158, 11));
        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabel10.setBackground(new java.awt.Color(245, 158, 11));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Endereço");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(74, 85, 104));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(245, 158, 11)));
        jPanel8.setForeground(new java.awt.Color(245, 158, 11));
        jPanel8.setOpaque(false);
        jPanel8.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabel11.setBackground(new java.awt.Color(245, 158, 11));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Contato");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel9.setOpaque(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel9.setText("E-mail:");

        txtTelfor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTelfor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 224, 224), 2, true));
        txtTelfor.setPreferredSize(new java.awt.Dimension(5, 30));
        txtTelfor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelforActionPerformed(evt);
            }
        });
        txtTelfor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelforKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel12.setText("Telefone:");

        txtEmailfor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmailfor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 224, 224), 2, true));
        txtEmailfor.setPreferredSize(new java.awt.Dimension(5, 30));
        txtEmailfor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailforActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTelfor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtEmailfor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addGap(0, 296, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmailfor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelfor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        clearforbTn.setBackground(new java.awt.Color(245, 158, 11));
        clearforbTn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clearforbTn.setForeground(new java.awt.Color(255, 255, 255));
        clearforbTn.setText("Limpar");
        clearforbTn.setFocusPainted(false);
        clearforbTn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearforbTnActionPerformed(evt);
            }
        });

        saveforbTn.setBackground(new java.awt.Color(16, 185, 129));
        saveforbTn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        saveforbTn.setForeground(new java.awt.Color(255, 255, 255));
        saveforbTn.setText("Salvar fornecedor");
        saveforbTn.setFocusPainted(false);
        saveforbTn.setPreferredSize(new java.awt.Dimension(112, 50));
        saveforbTn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveforbTnActionPerformed(evt);
            }
        });

        forcadbTn.setBackground(new java.awt.Color(59, 130, 246));
        forcadbTn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        forcadbTn.setForeground(new java.awt.Color(255, 255, 255));
        forcadbTn.setText("Fornecedores cadastrados");
        forcadbTn.setFocusPainted(false);
        forcadbTn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forcadbTnActionPerformed(evt);
            }
        });

        returnbTnfor.setBackground(new java.awt.Color(107, 114, 128));
        returnbTnfor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        returnbTnfor.setForeground(new java.awt.Color(255, 255, 255));
        returnbTnfor.setText("Voltar");
        returnbTnfor.setFocusPainted(false);
        returnbTnfor.setPreferredSize(new java.awt.Dimension(50, 40));
        returnbTnfor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbTnforActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveforbTn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(forcadbTn, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(returnbTnfor, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearforbTn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(returnbTnfor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearforbTn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveforbTn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(forcadbTn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeforActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeforActionPerformed

    private void txtCodigoforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoforActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoforActionPerformed

    private void txtCNPJforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCNPJforActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCNPJforActionPerformed

    private void txtNumforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumforActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumforActionPerformed

    private void txtCepforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCepforActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCepforActionPerformed

    private void txtTelforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelforActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelforActionPerformed

    private void txtEmailforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailforActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailforActionPerformed

    private void returnbTnforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbTnforActionPerformed
        Menu voltarmenu1 = new Menu();
        voltarmenu1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnbTnforActionPerformed

    private void clearforbTnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearforbTnActionPerformed
        limparCampos();
    }//GEN-LAST:event_clearforbTnActionPerformed

    private void saveforbTnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveforbTnActionPerformed
        try {
            //Valida os campos antes de salvar
            if (!validarCampos()) {
            return;
        }
            //Pega os valores dos campos
            String codigo = txtCodigofor.getText().trim();
            String nome = txtNomefor.getText().trim();
            String nomefant = txtNomefant.getText().trim();
            String cep = txtCepfor.getText().trim();
            String numero = txtNumfor.getText().trim();
            String email = txtEmailfor.getText().trim();
            String telefone = txtTelfor.getText().trim();
            String cnpj = txtCNPJfor.getText().trim();
            
            System.out.println("String nome" + nome);
       
        String sql = "INSERT INTO fornecedores (for_nome, for_nomefant, for_cnpj, for_cep, for_numero, for_email, for_telefone, for_datacad) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        try (Connection conexao = ConexaoSQL.getConexaoSQL();
            PreparedStatement pstmt = conexao.prepareStatement(sql)) {

            //define os valores de '?'
            pstmt.setString(1, nome);
            pstmt.setString(2, nomefant);
            pstmt.setString(3, cnpj);
            pstmt.setString(4, cep);
            pstmt.setString(5, numero);
            pstmt.setString(6, email);
            pstmt.setString(7, telefone);
            pstmt.setDate(8, new java.sql.Date(System.currentTimeMillis())); // data atual
            pstmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Fornecedor salvo com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);


        } catch (SQLException e) {
            //mensagem de erro
            JOptionPane.showMessageDialog(this, "Erro ao salvar o fornecedor no banco de dados.\n" + e.getMessage(), "Erro de Banco de Dados", JOptionPane.ERROR_MESSAGE);
        }
            
            //Verifica se o codigo do fornecedor ja existe
            if (codigoJaExiste(codigo)) {
                JOptionPane.showMessageDialog(this,
                        "Código já cadastrado! Tente outro.",
                        "Código duplicado",
                        JOptionPane.ERROR_MESSAGE);
                txtCodigofor.requestFocus();
                return;
            }
            //Cria o objeto Fornecedor
            Fornecedor novoFornecedor = new Fornecedor(codigo, nome, nomefant, cep, numero, email, telefone, cnpj);
            
            //Salva o fornecedor na lista
            fornecedores.add(novoFornecedor);
            
            //Mensagem de sucesso
            JOptionPane.showMessageDialog(this,
                "Fornecedor salvo com sucesso!",
                "Sucesso",
                JOptionPane.INFORMATION_MESSAGE);
            
            limparCampos();
            
            //Log de debug
            System.out.println("Fornecedor cadastrado:  " + novoFornecedor);
            System.out.println("Total de fornecedores: " + fornecedores.size());
          
          //Mensagem de erro
        } catch (HeadlessException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, 
                "Erro ao salvar o fornecedor: " + ex.getMessage(), 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
           
        }
    }//GEN-LAST:event_saveforbTnActionPerformed

    private void forcadbTnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forcadbTnActionPerformed
        TabelaFornecedores telaListagem = new TabelaFornecedores();
        telaListagem.setVisible(true);
    }//GEN-LAST:event_forcadbTnActionPerformed

    private void txtCepforKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCepforKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c) && c != '-' && c != java.awt.event.KeyEvent.VK_BACK_SPACE){
            evt.consume();
        }
    }//GEN-LAST:event_txtCepforKeyTyped

    private void txtNumforKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumforKeyTyped
        apenasNum(evt);
    }//GEN-LAST:event_txtNumforKeyTyped

    private void txtTelforKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelforKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c) && c != '(' && c != ')' && c != '-' && c != ' ' && c != java.awt.event.KeyEvent.VK_BACK_SPACE){
            evt.consume();
        }
    }//GEN-LAST:event_txtTelforKeyTyped

    private void txtCodigoforKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoforKeyTyped
        apenasNum(evt);
    }//GEN-LAST:event_txtCodigoforKeyTyped

    private void txtNomefantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomefantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomefantActionPerformed

    private void txtCNPJforKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCNPJforKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c) && c != '.' && c != '/' && c != java.awt.event.KeyEvent.VK_BACK_SPACE){
            evt.consume();
        }
    }//GEN-LAST:event_txtCNPJforKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CadastroFor().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearforbTn;
    private javax.swing.JButton forcadbTn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton returnbTnfor;
    private javax.swing.JButton saveforbTn;
    private javax.swing.JTextField txtCNPJfor;
    private javax.swing.JTextField txtCepfor;
    private javax.swing.JTextField txtCodigofor;
    private javax.swing.JTextField txtEmailfor;
    private javax.swing.JTextField txtNomefant;
    private javax.swing.JTextField txtNomefor;
    private javax.swing.JTextField txtNumfor;
    private javax.swing.JTextField txtTelfor;
    // End of variables declaration//GEN-END:variables
}
