package Telas;

import Classes.Cliente;
import Classes.ConexaoSQL;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author 2830482411041
 */
public class CadastroCl extends javax.swing.JFrame {

    // Lista estática para guardar os fornecedores
    private static List<Cliente> clientes = new ArrayList<>();

    public static List<Cliente> getClientes() {
        return clientes;
    }
    public CadastroCl() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

        private void apenasNum(java.awt.event.KeyEvent evt) {
            char c = evt.getKeyChar();
            if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
                evt.consume();
            }
        }
        
        private boolean validarCampos() {
        if (txtCodigocl.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, preencha o código do cliente!", 
                "Campo obrigatório", 
                JOptionPane.WARNING_MESSAGE);
            txtCodigocl.requestFocus();
            return false;
        }
        
        if (txtNomecl.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, preencha o nome do cliente!", 
                "Campo obrigatório", 
                JOptionPane.WARNING_MESSAGE);
            txtNomecl.requestFocus();
            return false;
        }
        
        if (txtCepcl.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, informe o CEP do cliente!", 
                "Campo obrigatório", 
                JOptionPane.WARNING_MESSAGE);
            txtCepcl.requestFocus();
            return false;
        }
        
        if (txtNumcl.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, informe o número do endereço!", 
                "Campo obrigatório", 
                JOptionPane.WARNING_MESSAGE);
            txtNumcl.requestFocus();
            return false;
        }
        
        if (txtEmailcl.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, informe o email do cliente!", 
                "Campo obrigatório", 
                JOptionPane.WARNING_MESSAGE);
            txtEmailcl.requestFocus();
            return false;
        }
        
        if (txtTelcl.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, informe o telefone do cliente!", 
                "Campo obrigatório", 
                JOptionPane.WARNING_MESSAGE);
            txtTelcl.requestFocus();
            return false;
        }
        return true;
    }

    
    /* Verifica se o código já existe na lista de clientes
     * return true se já existe, false caso não exista
     */
    private boolean codigoJaExiste(String codigo) {
        for (Cliente p : clientes) {
            if (p.getCodigo().equals(codigo)) {
                return true;
            }
        }
        return false;
    }
    
    private void limparCampos() {
        txtCodigocl.setText("");
        txtNomecl.setText("");
        txtEmailcl.setText("");
        txtNumcl.setText("");
        txtCepcl.setText("");
        txtTelcl.setText("");
        txtCodigocl.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNomecl = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCodigocl = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtNumcl = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCepcl = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtTelcl = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEmailcl = new javax.swing.JTextField();
        clearclbTn = new javax.swing.JButton();
        saveclbTn = new javax.swing.JButton();
        clcadbTn = new javax.swing.JButton();
        returnbTncl = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(4, 120, 87));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(483, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pczinho\\Downloads\\JAVAprojeto\\JAVAprojeto\\src\\icons\\icone_cliente.png")); // NOI18N
        jLabel1.setText("Cadastro de Clientes");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIconTextGap(8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(241, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(241, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(74, 85, 104));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel3.setForeground(new java.awt.Color(74, 85, 104));
        jPanel3.setOpaque(false);

        jPanel5.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setText("Código do cliente:");

        txtNomecl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNomecl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 224, 224), 2, true));
        txtNomecl.setPreferredSize(new java.awt.Dimension(5, 30));
        txtNomecl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeclActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setText("Nome:");

        txtCodigocl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCodigocl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 224, 224), 2, true));
        txtCodigocl.setPreferredSize(new java.awt.Dimension(5, 30));
        txtCodigocl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoclActionPerformed(evt);
            }
        });
        txtCodigocl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoclKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNomecl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(0, 211, Short.MAX_VALUE))
            .addComponent(txtCodigocl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigocl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomecl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jPanel6.setOpaque(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setText("CEP:");

        txtNumcl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNumcl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 224, 224), 2, true));
        txtNumcl.setPreferredSize(new java.awt.Dimension(5, 30));
        txtNumcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumclActionPerformed(evt);
            }
        });
        txtNumcl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumclKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setText("Número:");

        txtCepcl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCepcl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 224, 224), 2, true));
        txtCepcl.setPreferredSize(new java.awt.Dimension(5, 30));
        txtCepcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCepclActionPerformed(evt);
            }
        });
        txtCepcl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCepclKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNumcl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtCepcl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(0, 296, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCepcl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumcl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(74, 85, 104));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(4, 120, 87)));
        jPanel7.setForeground(new java.awt.Color(245, 158, 11));
        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabel10.setBackground(new java.awt.Color(245, 158, 11));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Endereço");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(74, 85, 104));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(4, 120, 87)));
        jPanel8.setForeground(new java.awt.Color(245, 158, 11));
        jPanel8.setOpaque(false);
        jPanel8.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabel11.setBackground(new java.awt.Color(245, 158, 11));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Contato");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel9.setOpaque(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel9.setText("E-mail:");

        txtTelcl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTelcl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 224, 224), 2, true));
        txtTelcl.setPreferredSize(new java.awt.Dimension(5, 30));
        txtTelcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelclActionPerformed(evt);
            }
        });
        txtTelcl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelclKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel12.setText("Telefone:");

        txtEmailcl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmailcl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 224, 224), 2, true));
        txtEmailcl.setPreferredSize(new java.awt.Dimension(5, 30));
        txtEmailcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailclActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTelcl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtEmailcl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addGap(0, 296, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmailcl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelcl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        clearclbTn.setBackground(new java.awt.Color(245, 158, 11));
        clearclbTn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clearclbTn.setForeground(new java.awt.Color(255, 255, 255));
        clearclbTn.setText("Limpar");
        clearclbTn.setFocusPainted(false);
        clearclbTn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearclbTnActionPerformed(evt);
            }
        });

        saveclbTn.setBackground(new java.awt.Color(16, 185, 129));
        saveclbTn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        saveclbTn.setForeground(new java.awt.Color(255, 255, 255));
        saveclbTn.setText("Salvar cliente");
        saveclbTn.setFocusPainted(false);
        saveclbTn.setPreferredSize(new java.awt.Dimension(112, 50));
        saveclbTn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveclbTnActionPerformed(evt);
            }
        });

        clcadbTn.setBackground(new java.awt.Color(59, 130, 246));
        clcadbTn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clcadbTn.setForeground(new java.awt.Color(255, 255, 255));
        clcadbTn.setText("Clientes cadastrados");
        clcadbTn.setFocusPainted(false);
        clcadbTn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clcadbTnActionPerformed(evt);
            }
        });

        returnbTncl.setBackground(new java.awt.Color(107, 114, 128));
        returnbTncl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        returnbTncl.setForeground(new java.awt.Color(255, 255, 255));
        returnbTncl.setText("Voltar");
        returnbTncl.setFocusPainted(false);
        returnbTncl.setPreferredSize(new java.awt.Dimension(50, 40));
        returnbTncl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbTnclActionPerformed(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(74, 85, 104));
        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(4, 120, 87)));
        jPanel10.setForeground(new java.awt.Color(245, 158, 11));
        jPanel10.setOpaque(false);
        jPanel10.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabel13.setBackground(new java.awt.Color(245, 158, 11));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Dados gerais");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveclbTn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(returnbTncl, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearclbTn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(clcadbTn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clearclbTn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(returnbTncl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveclbTn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clcadbTn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(528, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnbTnclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbTnclActionPerformed
        Menu voltarmenu1 = new Menu();
        voltarmenu1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnbTnclActionPerformed

    private void clcadbTnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clcadbTnActionPerformed
        TabelaClientes telaListagem = new TabelaClientes();
        telaListagem.setVisible(true);
    }//GEN-LAST:event_clcadbTnActionPerformed

    private void saveclbTnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveclbTnActionPerformed
        try {
            //Valida os campos antes de salvar
            if (!validarCampos()) {
                return;
            }
            //Pega os valores dos campos
            String codigo = txtCodigocl.getText().trim();
            String nome = txtNomecl.getText().trim();
            String cep = txtCepcl.getText().trim();
            String numero = txtNumcl.getText().trim();
            String email = txtEmailcl.getText().trim();
            String telefone = txtTelcl.getText().trim();

            System.out.println("String nome" + nome);

            String sql = "INSERT INTO clientes (cl_nome, cl_cep, cl_numero, cl_email, cl_telefone, cl_datacad) VALUES (?, ?, ?, ?, ?, ?)";
            try (Connection conexao = ConexaoSQL.getConexaoSQL();
                PreparedStatement pstmt = conexao.prepareStatement(sql)) {

                //define os valores de '?'
                pstmt.setString(1, nome);
                pstmt.setString(2, cep);
                pstmt.setString(3, numero);
                pstmt.setString(4, email);
                pstmt.setString(5, telefone);
                pstmt.setDate(6, new java.sql.Date(System.currentTimeMillis())); // data atual
                pstmt.executeUpdate();

                JOptionPane.showMessageDialog(this, "Cliente salvo com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            } catch (SQLException e) {
                //mensagem de erro
                JOptionPane.showMessageDialog(this, "Erro ao salvar o cliente no banco de dados.\n" + e.getMessage(), "Erro de Banco de Dados", JOptionPane.ERROR_MESSAGE);
            }

            //Verifica se o codigo do cliente ja existe
            if (codigoJaExiste(codigo)) {
                JOptionPane.showMessageDialog(this,
                    "Código já cadastrado! Tente outro.",
                    "Código duplicado",
                    JOptionPane.ERROR_MESSAGE);
                txtCodigocl.requestFocus();
                return;
            }
            //Cria o objeto Cliente
            Cliente novoCliente = new Cliente(codigo, nome, cep, numero, email, telefone);

            //Salva o cliente na lista
            clientes.add(novoCliente);

            limparCampos();

            //Log de debug
            System.out.println("Cliente cadastrado:  " + novoCliente);
            System.out.println("Total de clientes: " + clientes.size());

            //Mensagem de erro
        } catch (HeadlessException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                "Erro ao salvar o cliente:" + ex.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveclbTnActionPerformed

    private void clearclbTnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearclbTnActionPerformed
        limparCampos();
    }//GEN-LAST:event_clearclbTnActionPerformed

    private void txtEmailclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailclActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailclActionPerformed

    private void txtTelclKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelclKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c) && c != '(' && c != ')' && c != '-' && c != ' ' && c != java.awt.event.KeyEvent.VK_BACK_SPACE){
            evt.consume();
        }
    }//GEN-LAST:event_txtTelclKeyTyped

    private void txtTelclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelclActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelclActionPerformed

    private void txtCepclKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCepclKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c) && c != '-' && c != java.awt.event.KeyEvent.VK_BACK_SPACE){
            evt.consume();
        }
    }//GEN-LAST:event_txtCepclKeyTyped

    private void txtCepclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCepclActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCepclActionPerformed

    private void txtNumclKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumclKeyTyped
        apenasNum(evt);
    }//GEN-LAST:event_txtNumclKeyTyped

    private void txtNumclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumclActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumclActionPerformed

    private void txtCodigoclKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoclKeyTyped
        apenasNum(evt);
    }//GEN-LAST:event_txtCodigoclKeyTyped

    private void txtCodigoclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoclActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoclActionPerformed

    private void txtNomeclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeclActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeclActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clcadbTn;
    private javax.swing.JButton clearclbTn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton returnbTncl;
    private javax.swing.JButton saveclbTn;
    private javax.swing.JTextField txtCepcl;
    private javax.swing.JTextField txtCodigocl;
    private javax.swing.JTextField txtEmailcl;
    private javax.swing.JTextField txtNomecl;
    private javax.swing.JTextField txtNumcl;
    private javax.swing.JTextField txtTelcl;
    // End of variables declaration//GEN-END:variables
}
